/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Annisaa Utami
 */
public class Choose extends javax.swing.JFrame {

    int xMouse,yMouse;
    
    public Choose() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameDrag = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        Decrypt = new javax.swing.JLabel();
        Encrypt = new javax.swing.JLabel();
        Bg2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FrameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FrameDragMouseDragged(evt);
            }
        });
        FrameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FrameDragMousePressed(evt);
            }
        });
        getContentPane().add(FrameDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 950, 40));

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Back.png"))); // NOI18N
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackMouseExited(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        Decrypt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Decrypt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DecryptMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DecryptMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DecryptMouseReleased(evt);
            }
        });
        getContentPane().add(Decrypt, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 55, 380, 650));

        Encrypt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Encrypt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EncryptMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EncryptMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EncryptMouseExited(evt);
            }
        });
        getContentPane().add(Encrypt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 55, 380, 650));

        Bg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Choice.png"))); // NOI18N
        getContentPane().add(Bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        new Main().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackMouseClicked

    private void BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Back2.png"));
        Back.setIcon(II);
    }//GEN-LAST:event_BackMouseEntered

    private void BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Back.png"));
        Back.setIcon(II);
    }//GEN-LAST:event_BackMouseExited

    private void DecryptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DecryptMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Image/Choice1.2.png"));
        Bg2.setIcon(II);
    }//GEN-LAST:event_DecryptMouseEntered

    private void DecryptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DecryptMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Image/Choice.png"));
        Bg2.setIcon(II);
    }//GEN-LAST:event_DecryptMouseExited

    private void DecryptMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DecryptMouseReleased
        try  {
            this.setVisible(false);
            new Decrypt().setVisible(true);
        } catch (Exception ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_DecryptMouseReleased

    private void EncryptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EncryptMouseClicked
        try  {
                this.setVisible(false);
                new Encrypt().setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_EncryptMouseClicked

    private void EncryptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EncryptMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Image/Choice1.1.png"));
        Bg2.setIcon(II);
    }//GEN-LAST:event_EncryptMouseEntered

    private void EncryptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EncryptMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Image/Choice.png"));
        Bg2.setIcon(II);
    }//GEN-LAST:event_EncryptMouseExited

    private void FrameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_FrameDragMouseDragged

    private void FrameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_FrameDragMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Choose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Bg2;
    private javax.swing.JLabel Decrypt;
    private javax.swing.JLabel Encrypt;
    private javax.swing.JLabel FrameDrag;
    // End of variables declaration//GEN-END:variables
}
