/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.crypto.Cipher;
import javax.crypto.CipherOutputStream;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Muhamad Dio
 */
public class Decrypt extends javax.swing.JFrame {

    int xMouse, yMouse;
    File file, savefile;
    JFileChooser fc, fs;
    int p;
    
    public Decrypt() {
        initComponents();
        this.setLocationRelativeTo(null);
        fc = new JFileChooser();
            fs = new JFileChooser();
            //Setting fc untuk ke file yang ditentukan);
            //fc.addChoosableFileFilter(new ImageFilter());
           // fs.addChoosableFileFilter(new pngFilter());
            fc.setAcceptAllFileFilterUsed(false);
            fs.setAcceptAllFileFilterUsed(false);
            //Menambah icon untuk file yang sesuai
              // fc.setFileView(new ImageFileView());
                //Menambahkan preview pane/jendela
              //  fc.setAccessory(new ImagePreview(fc));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Home = new javax.swing.JLabel();
        txt_key = new javax.swing.JPasswordField();
        Eye = new javax.swing.JLabel();
        txt_Choose = new javax.swing.JLabel();
        Choose = new javax.swing.JLabel();
        FrameDrag = new javax.swing.JLabel();
        Decrypt = new javax.swing.JLabel();
        Key = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Gambar = new javax.swing.JLabel();
        Reset = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(216, 226, 220));
        jPanel1.setLayout(null);

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Back1.png"))); // NOI18N
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMouseExited(evt);
            }
        });
        jPanel1.add(Home);
        Home.setBounds(20, 10, 50, 70);

        txt_key.setBackground(new java.awt.Color(255, 202, 212));
        txt_key.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txt_key.setForeground(new java.awt.Color(157, 129, 137));
        txt_key.setBorder(null);
        jPanel1.add(txt_key);
        txt_key.setBounds(290, 650, 320, 60);

        Eye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/view2.png"))); // NOI18N
        Eye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EyeMouseClicked(evt);
            }
        });
        jPanel1.add(Eye);
        Eye.setBounds(630, 660, 40, 40);

        txt_Choose.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txt_Choose.setForeground(new java.awt.Color(157, 129, 137));
        jPanel1.add(txt_Choose);
        txt_Choose.setBounds(370, 540, 350, 70);

        Choose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Choose.png"))); // NOI18N
        Choose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Choose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChooseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ChooseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ChooseMouseExited(evt);
            }
        });
        jPanel1.add(Choose);
        Choose.setBounds(50, 510, 680, 130);

        FrameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FrameDragMouseDragged(evt);
            }
        });
        FrameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FrameDragMousePressed(evt);
            }
        });
        jPanel1.add(FrameDrag);
        FrameDrag.setBounds(0, 0, 1024, 40);

        Decrypt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Decrypt.png"))); // NOI18N
        Decrypt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Decrypt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DecryptMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DecryptMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DecryptMouseExited(evt);
            }
        });
        jPanel1.add(Decrypt);
        Decrypt.setBounds(740, 520, 270, 100);

        Key.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Key1.png"))); // NOI18N
        Key.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Key.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                KeyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                KeyMouseExited(evt);
            }
        });
        jPanel1.add(Key);
        Key.setBounds(50, 630, 640, 100);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(157, 129, 137));
        jLabel1.setText("DECRYPT");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 20, 250, 50);
        jPanel1.add(Gambar);
        Gambar.setBounds(90, 100, 840, 400);

        Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Reset.png"))); // NOI18N
        Reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ResetMouseExited(evt);
            }
        });
        jPanel1.add(Reset);
        Reset.setBounds(740, 630, 270, 110);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FrameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_FrameDragMouseDragged

    private void FrameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
        
    }//GEN-LAST:event_FrameDragMousePressed

    private void KeyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeyMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Key1.2.png"));
        Key.setIcon(II);
    }//GEN-LAST:event_KeyMouseEntered

    private void KeyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeyMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Key1.png"));
        Key.setIcon(II);
    }//GEN-LAST:event_KeyMouseExited

    private void DecryptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DecryptMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Decrypt2.png"));
        Decrypt.setIcon(II);
    }//GEN-LAST:event_DecryptMouseEntered

    private void DecryptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DecryptMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Decrypt.png"));
        Decrypt.setIcon(II);
    }//GEN-LAST:event_DecryptMouseExited

    private void ChooseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChooseMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Choose2.png"));
        Choose.setIcon(II);
    }//GEN-LAST:event_ChooseMouseEntered

    private void ChooseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChooseMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Choose.png"));
        Choose.setIcon(II);
    }//GEN-LAST:event_ChooseMouseExited

    private void ChooseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChooseMouseClicked
       JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        txt_Choose.setText(f.getAbsolutePath());
    }//GEN-LAST:event_ChooseMouseClicked

    private void EyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EyeMouseClicked
        if(p==1){
        txt_key.setEchoChar((char)0);
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/hide2.png"));
        Eye.setIcon(II);
        p=2;
        }
        else{
            txt_key.setEchoChar('*');
            ImageIcon II = new ImageIcon(getClass().getResource("/Button/view2.png"));
            Eye.setIcon(II);
            p=1;
        }
    }//GEN-LAST:event_EyeMouseClicked

    private void HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Back1.2.png"));
        Home.setIcon(II);
    }//GEN-LAST:event_HomeMouseEntered

    private void HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Back1.png"));
        Home.setIcon(II);
    }//GEN-LAST:event_HomeMouseExited

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        this.setVisible(false);
        
        new Choose().setVisible(true);
    }//GEN-LAST:event_HomeMouseClicked

    private void DecryptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DecryptMouseClicked
        try{
        int returnValue = fs.showSaveDialog(Decrypt.this);
        if(returnValue == JFileChooser.APPROVE_OPTION)
        {
        savefile = fs.getSelectedFile();
        String saveFileName = "" +savefile;
        int saveFileLength = saveFileName.length();
        
        if(saveFileLength<4)
            saveFileName += ".jpg";
        if(saveFileName.charAt(saveFileLength-4)!='.'
                && saveFileName.charAt(saveFileLength-3)!='j'
                && saveFileName.charAt(saveFileLength-2)!='p'
                && saveFileName.charAt(saveFileLength-1)!='g')
                saveFileName += ".jpg";
                saveFileLength = saveFileName.length();
        
            FileInputStream file = new FileInputStream(txt_Choose.getText());
            FileOutputStream outStream = new FileOutputStream(saveFileName);
            String j = txt_key.getText();
            byte k[]=j.getBytes();
            SecretKeySpec key = new SecretKeySpec(k, "DES");
            Cipher enc = Cipher.getInstance("DES");
            enc.init(Cipher.DECRYPT_MODE, key);
            CipherOutputStream cos = new CipherOutputStream(outStream, enc);
            byte[] buf = new byte[1024];
            int read;
            while((read=file.read(buf))!=-1){
            cos.write(buf,0,read);
        }
            file.close();
            outStream.flush();
            cos.close();
            JOptionPane.showMessageDialog(null, "The image was decrypted Successfully");
            
            ImageIcon imIco = new ImageIcon(saveFileName);
            Image imFit = imIco.getImage();
            Image imgFit = imFit.getScaledInstance(Gambar.getWidth(),Gambar.getHeight(), Image.SCALE_SMOOTH);
            Gambar.setIcon(new ImageIcon(imgFit));
            }
        else
            return;

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_DecryptMouseClicked

    private void ResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseClicked
        txt_Choose.setText("");
        txt_key.setText("");
    }//GEN-LAST:event_ResetMouseClicked

    private void ResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Reset2.png"));
        Reset.setIcon(II);
    }//GEN-LAST:event_ResetMouseEntered

    private void ResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Reset.png"));
        Reset.setIcon(II);
    }//GEN-LAST:event_ResetMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Decrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Decrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Decrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Decrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Decrypt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Choose;
    private javax.swing.JLabel Decrypt;
    private javax.swing.JLabel Eye;
    private javax.swing.JLabel FrameDrag;
    private javax.swing.JLabel Gambar;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Key;
    private javax.swing.JLabel Reset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt_Choose;
    private javax.swing.JPasswordField txt_key;
    // End of variables declaration//GEN-END:variables
}
