/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.math.BigInteger;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.CipherOutputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;

/**
 *
 * @author Muhamad Dio
 */
public class Encrypt extends javax.swing.JFrame {

    int xMouse,yMouse;
    File file, savefile;
    JFileChooser fc, fs;
    int p;
        
    public Encrypt() {
        initComponents();
        this.setLocationRelativeTo(null);
        fc = new JFileChooser();
            fs = new JFileChooser();
            //Setting fc untuk ke file yang ditentukan);
            //fc.addChoosableFileFilter(new ImageFilter());
           // fs.addChoosableFileFilter(new pngFilter());
            fc.setAcceptAllFileFilterUsed(false);
            fs.setAcceptAllFileFilterUsed(false);
            //Menambah icon untuk file yang sesuai
              // fc.setFileView(new ImageFileView());
                //Menambahkan preview pane/jendela
              //  fc.setAccessory(new ImagePreview(fc));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FrameDrag = new javax.swing.JLabel();
        Eye = new javax.swing.JLabel();
        Txt_Key = new javax.swing.JPasswordField();
        Key = new javax.swing.JLabel();
        txt_image = new javax.swing.JLabel();
        Choose = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Encrypt = new javax.swing.JLabel();
        Reset = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(216, 226, 220));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setBackground(new java.awt.Color(216, 226, 220));
        Background.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(157, 129, 137));
        jLabel1.setText("ENCRYPT");
        Background.add(jLabel1);
        jLabel1.setBounds(100, 20, 260, 70);

        FrameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FrameDragMouseDragged(evt);
            }
        });
        FrameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FrameDragMousePressed(evt);
            }
        });
        Background.add(FrameDrag);
        FrameDrag.setBounds(0, 0, 1024, 40);

        Eye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/view.png"))); // NOI18N
        Eye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EyeMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                EyeMouseReleased(evt);
            }
        });
        Background.add(Eye);
        Eye.setBounds(880, 330, 60, 50);

        Txt_Key.setBackground(new java.awt.Color(255, 202, 212));
        Txt_Key.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Txt_Key.setForeground(new java.awt.Color(157, 129, 137));
        Txt_Key.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Txt_Key.setOpaque(false);
        Txt_Key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_KeyActionPerformed(evt);
            }
        });
        Background.add(Txt_Key);
        Txt_Key.setBounds(420, 330, 450, 50);

        Key.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Key.png"))); // NOI18N
        Key.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Key.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                KeyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                KeyMouseExited(evt);
            }
        });
        Background.add(Key);
        Key.setBounds(100, 300, 850, 110);

        txt_image.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txt_image.setForeground(new java.awt.Color(157, 129, 137));
        Background.add(txt_image);
        txt_image.setBounds(420, 170, 510, 50);

        Choose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Choose.png"))); // NOI18N
        Choose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Choose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChooseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ChooseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ChooseMouseExited(evt);
            }
        });
        Background.add(Choose);
        Choose.setBounds(100, 140, 850, 110);

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Back1.png"))); // NOI18N
        Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMouseExited(evt);
            }
        });
        Background.add(Home);
        Home.setBounds(20, 20, 50, 70);

        Encrypt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Encrypt.png"))); // NOI18N
        Encrypt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Encrypt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EncryptMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EncryptMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EncryptMouseExited(evt);
            }
        });
        Background.add(Encrypt);
        Encrypt.setBounds(670, 570, 270, 110);

        Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Reset.png"))); // NOI18N
        Reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ResetMouseExited(evt);
            }
        });
        Background.add(Reset);
        Reset.setBounds(370, 570, 270, 110);

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FrameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_FrameDragMouseDragged

    private void FrameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_FrameDragMousePressed

    private void ChooseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChooseMouseClicked
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        txt_image.setText(f.getAbsolutePath());
    }//GEN-LAST:event_ChooseMouseClicked

    private void ChooseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChooseMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Choose2.png"));
        Choose.setIcon(II);
    }//GEN-LAST:event_ChooseMouseEntered

    private void ChooseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChooseMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Choose.png"));
        Choose.setIcon(II);
    }//GEN-LAST:event_ChooseMouseExited

    private void KeyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeyMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Key2.png"));
        Key.setIcon(II);
    }//GEN-LAST:event_KeyMouseEntered

    private void KeyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeyMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Key.png"));
        Key.setIcon(II);
    }//GEN-LAST:event_KeyMouseExited

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        this.setVisible(false);
        
        new Choose().setVisible(true);
    }//GEN-LAST:event_HomeMouseClicked

    private void HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Back1.2.png"));
        Home.setIcon(II);
    }//GEN-LAST:event_HomeMouseEntered

    private void HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Back1.png"));
        Home.setIcon(II);
    }//GEN-LAST:event_HomeMouseExited

    private void EncryptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EncryptMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Encrypt2.png"));
        Encrypt.setIcon(II);
    }//GEN-LAST:event_EncryptMouseEntered
    
    private void EncryptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EncryptMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Encrypt.png"));
        Encrypt.setIcon(II);
    }//GEN-LAST:event_EncryptMouseExited

    private void Txt_KeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_KeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_KeyActionPerformed

    private void EyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EyeMouseClicked
        if(p==1){
        Txt_Key.setEchoChar((char)0);
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/hide.png"));
        Eye.setIcon(II);
        p=2;
        }
        else{
            Txt_Key.setEchoChar('*');
            ImageIcon II = new ImageIcon(getClass().getResource("/Button/view.png"));
            Eye.setIcon(II);
            p=1;
        }
    }//GEN-LAST:event_EyeMouseClicked

    private void EyeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EyeMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_EyeMouseReleased

    private void EncryptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EncryptMouseClicked
        try{
        int returnValue = fs.showSaveDialog(Encrypt.this);
        if(returnValue == JFileChooser.APPROVE_OPTION)
        {
        savefile = fs.getSelectedFile();
        String saveFileName = "" +savefile;
        int saveFileLength = saveFileName.length();
        
        if(saveFileLength<4)
            saveFileName += ".jpg";
        if(saveFileName.charAt(saveFileLength-4)!='.'
                && saveFileName.charAt(saveFileLength-3)!='j'
                && saveFileName.charAt(saveFileLength-2)!='p'
                && saveFileName.charAt(saveFileLength-1)!='g')
            saveFileName += ".jpg";
        saveFileLength = saveFileName.length();
        
            FileInputStream file = new FileInputStream(txt_image.getText());
            FileOutputStream outStream = new FileOutputStream(saveFileName);
            String j = Txt_Key.getText(); //Key
            byte k[]= j.getBytes(); //Mengambil bit Key
            SecretKeySpec key = new SecretKeySpec(k, "DES"); //
            Cipher enc = Cipher.getInstance("DES"); //
            enc.init(Cipher.ENCRYPT_MODE, key); //
            CipherOutputStream cos = new CipherOutputStream(outStream, enc);
            byte[] buf = new byte[1024];
            int read;
            while((read=file.read(buf))!=-1){
            cos.write(buf,0,read);            
            }
            file.close();
            outStream.flush();
            cos.close();
            JOptionPane.showMessageDialog(null, "The File Encrypted Successfully");
            }
        else
            return;
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_EncryptMouseClicked

    private void ResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseClicked
        Txt_Key.setText("");
        txt_image.setText("");
    }//GEN-LAST:event_ResetMouseClicked

    private void ResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Reset2.png"));
        Reset.setIcon(II);
    }//GEN-LAST:event_ResetMouseEntered

    private void ResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Button/Reset.png"));
        Reset.setIcon(II);
    }//GEN-LAST:event_ResetMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Encrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Encrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Encrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Encrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Encrypt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Choose;
    private javax.swing.JLabel Encrypt;
    private javax.swing.JLabel Eye;
    private javax.swing.JLabel FrameDrag;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Key;
    private javax.swing.JLabel Reset;
    private javax.swing.JPasswordField Txt_Key;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txt_image;
    // End of variables declaration//GEN-END:variables
}
