/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import javax.swing.ImageIcon;

/**
 *
 * @author ASUS
 */
public class Help extends javax.swing.JFrame {

    /**
     * Creates new form Help
     */
    
    int e=1;
    int xMouse, yMouse;
    
    
    public Help() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Decrypt = new javax.swing.JLabel();
        Encrypt = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        FrameDrag = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 100));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Decrypt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/HelpDecrypt.png"))); // NOI18N
        Decrypt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Decrypt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DecryptMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DecryptMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DecryptMouseExited(evt);
            }
        });
        getContentPane().add(Decrypt, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 320, 270));

        Encrypt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/HelpEncrypt.png"))); // NOI18N
        Encrypt.setToolTipText("");
        Encrypt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Encrypt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EncryptMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EncryptMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EncryptMouseExited(evt);
            }
        });
        getContentPane().add(Encrypt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 320, 270));

        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 80, 50));

        FrameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                FrameDragMouseDragged(evt);
            }
        });
        FrameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FrameDragMousePressed(evt);
            }
        });
        getContentPane().add(FrameDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 40));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/HelpBG.png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        if(e==1){
        this.setVisible(false);
        }
        else{
            ImageIcon IZ = new ImageIcon(getClass().getResource("/Image/HelpBG.png"));
            BG.setIcon(IZ);
            Decrypt.setVisible(true);
            Encrypt.setVisible(true);
            
            e=1;
        }
    }//GEN-LAST:event_ExitMouseClicked

    private void FrameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_FrameDragMouseDragged

    private void FrameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameDragMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_FrameDragMousePressed

    private void EncryptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EncryptMouseEntered
        ImageIcon IZ = new ImageIcon(getClass().getResource("/Image/HelpEncrypt2.png"));
        Encrypt.setIcon(IZ);
    }//GEN-LAST:event_EncryptMouseEntered

    private void EncryptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EncryptMouseExited
        ImageIcon IZ = new ImageIcon(getClass().getResource("/Image/HelpEncrypt.png"));
        Encrypt.setIcon(IZ);
    }//GEN-LAST:event_EncryptMouseExited

    private void DecryptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DecryptMouseEntered
        ImageIcon IZ = new ImageIcon(getClass().getResource("/Image/HelpDecrypt2.png"));
        Decrypt.setIcon(IZ);
    }//GEN-LAST:event_DecryptMouseEntered

    private void DecryptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DecryptMouseExited
        ImageIcon IZ = new ImageIcon(getClass().getResource("/Image/HelpDecrypt.png"));
        Decrypt.setIcon(IZ);
    }//GEN-LAST:event_DecryptMouseExited

    private void EncryptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EncryptMouseClicked
     
        ImageIcon IZ = new ImageIcon(getClass().getResource("/Image/HelpENC.png"));
        BG.setIcon(IZ);
        Decrypt.setVisible(false);
        Encrypt.setVisible(false);
        e=2;
        
    }//GEN-LAST:event_EncryptMouseClicked

    private void DecryptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DecryptMouseClicked
        ImageIcon IZ = new ImageIcon(getClass().getResource("/Image/HelpDEC.png"));
        BG.setIcon(IZ);
        Decrypt.setVisible(false);
        Encrypt.setVisible(false);
        e=2;
    }//GEN-LAST:event_DecryptMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Help().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Decrypt;
    private javax.swing.JLabel Encrypt;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel FrameDrag;
    // End of variables declaration//GEN-END:variables
}
